In [2]:
import pandas as pd


im_data = pd.read_csv('../Data/result_6.csv')
dummpy_data = pd.DataFrame()
for col in im_data.columns:
    if im_data[col].ftype == 'int64:dense' and len(im_data[col].unique()) > 2:
        dummpy = pd.get_dummies(im_data[col])
        col_name = [col+'_'+str(i) for i in dummpy.columns]
        dummpy.columns = col_name
        for col_ in dummpy.columns:
            dummpy_data[col_] = dummpy[col_]
            
    else:
        dummpy_data[col] = im_data[col]
        
im_data = dummpy_data
im_data.to_csv('../Data/result_6_dummpy.csv', encoding='utf-8_sig', index=False)
im_data.head()

,AMT_CREDIT,DAYS_BIRTH,HOUR_APPR_PROCESS_START,REGION_POPULATION_RELATIVE,AMT_REQ_CREDIT_BUREAU_YEAR,EXT_SOURCE_3,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLOORSMAX_AVG,DAYS_LAST_PHONE_CHANGE,...,ORGANIZATION_TYPE_52,ORGANIZATION_TYPE_53,ORGANIZATION_TYPE_54,ORGANIZATION_TYPE_55,ORGANIZATION_TYPE_56,ORGANIZATION_TYPE_57,CODE_GENDER_0,CODE_GENDER_1,CODE_GENDER_2,TARGET
0,0.090287,0.888839,0.434783,0.256321,0.040000,0.155054,0.852140,0.705433,0.083300,0.735788,...,0,0,0,0,0,0,1,0,0,1
1,0.311736,0.477114,0.478261,0.045016,0.000000,0.569889,0.951929,0.959566,0.291700,0.807083,...,0,0,0,0,0,0,0,1,0,0
2,0.022472,0.348534,0.391304,0.134897,0.000000,0.814130,0.827335,0.648326,0.226282,0.810112,...,0,0,0,0,0,0,1,0,0,0
3,0.066837,0.350846,0.739130,0.107023,0.075999,0.569889,0.601451,0.661387,0.226282,0.856244,...,0,0,0,0,0,0,0,1,0,0
4,0.116854,0.298591,0.478261,0.392880,0.000000,0.569889,0.825268,0.519522,0.226282,0.742311,...,0,0,0,0,0,0,1,0,0,0